version: '3'

services:
  pokedex-api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-api-docker
    container_name: pokedex-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}

  db:
    image: mongo:8
    container_name: mongo-pokedex
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: pokedex
    volumes:
      - ./mongo:/data/db
